config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit update destroy]
  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_flat_form.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name, label: "Name" %>
  <%= f.input :address, label: "Address" %>
  <%= f.input :description, label: "Description" %>
  <%= f.input :price_per_night, label: "Price per night" %>
  <%= f.input :number_of_guests, label: "Number of guests" %>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/flats/edit.html.erb
<h3 class='text-center mt-3'>Edit a flat</h3>


<%= render 'flat_form', flat: @flat %>

app/views/flats/index.html.erb
<h1 class="text-center mt-3 mb-5">All Flats</h1>
<div class="row">
<% @flats.each do |flat| %>
<div class="col-md-4">
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title"><%= flat.name %></h5>
    <p class="card-text">
      <strong>Address:</strong> <%= flat.address %><br>
      <strong>Description:</strong> <%= flat.description %>
    </p>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <strong>Price per night:</strong> <%= flat.price_per_night %>
      </li>
      <li class="list-group-item">
        <strong>Number of guests:</strong> <%= flat.number_of_guests %>
      </li>
      <li class="list-group-item">
        <%= link_to "More info", flat_path(flat), class: "link-primary mt-2" %>
        <%= link_to "Edit", edit_flat_path(flat), class: "link-warning mt-2" %>
        <%= link_to "Delete", flat_path(flat), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "link-danger mt-2" %>
      </li>
    </ul>
  </div>
</div>
</div>
<% end %>
</div>

app/views/flats/new.html.erb
<h3 class='text-center mt-3'>Create a new flat</h3>

<%= render 'flat_form', flat: @flat %>

app/views/flats/show.html.erb
<h3 class='text-center m-3'>Flat details</h3>
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= @flat.name %></h5>
    <p class="card-text">
      <strong>Address:</strong> <%= @flat.address %><br>
      <strong>Description:</strong> <%= @flat.description %>
    </p>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <strong>Price per night:</strong> <%= @flat.price_per_night %>
      </li>
      <li class="list-group-item">
        <strong>Number of guests:</strong> <%= @flat.number_of_guests %>
      </li>
    </ul>
    <div class="card-footer text-muted">
       <%= link_to "Edit", edit_flat_path(@flat), class: "btn btn-success" %>
       <%= link_to "Delete", flat_path(@flat), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>
    </div>
  </div>
</div>

<%= link_to "Back to all flats", flats_path, class: "btn btn-secondary mt-3" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>